
nick_name: MainExperiment
device: cuda:0
seed: 25
result_base_dir: "results"


data:
  data_path: /home/xiangcen/SPRV_Brain/data/BraTs_H5

  total_number: 2251

  meta_train_number: 2000
  support_set_number: 1000
  query_set_number: 1000
  

  meta_test_number: 251
  development_set_number: 150
  estimation_set_number: 101



segmentation:
  batch_size: 6
  epoch: 500
  shuffle: True
  drop_last: False
  learning_rate: 0.0001
  


ranking:
  epoch: 2000
  batch_size: 1
  sequence_length: 8
  shuffle: True
  drop_last: True
  learning_rate: 0.0005
  


workflow_evaluation:
  pre_train: True
  t_values: [0.95, 0.9, 0.8, 0.6, 0.4, 0.3]
