
nick_name: MainExperiment
device: cuda:0
seed: 25
result_base_dir: "results"
img_size: [64, 64, 64]


data:
  data_path: /home/xiangcen/SPRV_Brain/data/BraTs_H5

  total_number: 2251

  meta_train_number: 2000
  support_set_number: 1000
  query_set_number: 1000
  

  meta_test_number: 251
  development_set_number: 101
  estimation_set_number: 150



segmentation:
  batch_size: 6
  epoch: 100
  shuffle: True
  drop_last: False
  learning_rate: 0.0001
  num_channel: 4
  


ranking:
  epoch: 1000
  batch_size: 1
  sequence_length: 8
  shuffle: True
  drop_last: True
  learning_rate: 0.01
  token_length: 4096
  num_channel: 5
  


workflow_evaluation:
  pre_train: True
  t_values: [0.95, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3]
  seg_lr: 0.001
  seg_epoch: 1
  num_experiments: 1

